name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest'
    permissions:
      contents: read
      packages: write # Allow CI to write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner_id }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute image in lowercase
        id: compute
        run: |
          image_lower=$(echo "ghcr.io/${{ github.repository }}/app:latest" | tr '[:upper:]' '[:lower:]')
          echo "image=$image_lower" >> "$GITHUB_OUTPUT"
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.compute.outputs.image }}